environment:
  n_leader: 1              # Leader 数量
  n_follower: 2            # Follower 数量（自定义配置）
  render: false            # 是否渲染可视化
  state_dim: 7             # 状态维度

training:
  device: 'auto'           # 设备选择
  seed: 42                 # 随机种子

# ============================================
# 测试配置
# ============================================
testing:
  test_episode: 20         # 测试轮数（快速测试）
  ep_len: 1000             # 每轮最大步数
  render: false            # 是否渲染可视化

  # 模型路径 - 替换为你想要测试的权重文件
  leader_model_path: 'runs/YOUR_EXPERIMENT/leader.pth'
  follower_model_path: 'runs/YOUR_EXPERIMENT/follower.pth'

# ============================================
# 网络配置
# ============================================
network:
  hidden_dim: 256          # 隐藏层维度
  policy_lr: 1.0e-3        # 学习率

env_vars:
  KMP_DUPLICATE_LIB_OK: 'TRUE'
